import math


PHASE_NUM = 512
TAP_NUM = 8
FRAC_BITS = 14
SCALE = 1 << FRAC_BITS

TAP_OFFSETS = [-3, -2, -1, 0, 1, 2, 3, 4]
OUT_FILE = "pp_downscale_lanczos4_coef_rom_table.vh"


def sinc(x):
    if abs(x) < 1e-12:
        return 1.0
    return math.sin(math.pi * x) / (math.pi * x)


def lanczos4(x):
    if abs(x) >= 4.0:
        return 0.0
    return sinc(x) * sinc(x / 4.0)


def quantize_q2_14(coefs):
    q = [int(round(c * SCALE)) for c in coefs]

    # Keep DC gain exactly 1.0 in Q2.14 after integer quantization.
    diff = SCALE - sum(q)
    max_idx = max(range(TAP_NUM), key=lambda i: abs(q[i]))
    q[max_idx] += diff

    for value in q:
        if value < -32768 or value > 32767:
            raise ValueError(f"Q2.14 coefficient out of int16 range: {value}")

    return q


def verilog_s16(value):
    if value < 0:
        return f"-16'sd{-value}"
    return f"16'sd{value}"


def main():
    with open(OUT_FILE, "w", encoding="ascii", newline="\n") as f:
        f.write("// Auto-generated by gen_lanczos4_coef_q2_14.py\n")
        f.write("// Lanczos4 coefficients, phase precision 1/512, signed Q2.14.\n")
        f.write("// Tap order: -3, -2, -1, 0, +1, +2, +3, +4.\n\n")

        for phase_i in range(PHASE_NUM):
            phase = phase_i / PHASE_NUM
            coefs = [lanczos4(phase - offset) for offset in TAP_OFFSETS]
            qcoefs = quantize_q2_14(coefs)

            f.write(f"        9'd{phase_i}: begin\n")
            for tap_i, coef in enumerate(qcoefs):
                f.write(f"            coef{tap_i} = {verilog_s16(coef)};\n")
            f.write("        end\n")


if __name__ == "__main__":
    main()
